<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ConnectivesSeeder extends Seeder
{
    public function run()
    {
        $connectives = [
            [
                'name' => 'و', 
                'transliteration' => 'wa', 
                'pronunciation' => '/wa:/', 
                'meaning' => 'و',
                'definition' => 'تربط بين عنصرين أو أكثر في قائمة أو جمل.',
                'category_id' => 1, // حروف العطف
                'syntactic_effect_id' => 1,
                'semantic_logical_effect_id' => 1,
                'morphological_form' => 'جزء',
                'typical_nisbah' => 'واو',
                'primary_usage' => 'الإضافة',
                'grammatical_function' => 'رابط',
                'position' => 'middle',
                'connective_form' => 'standalone',
                'is_classical' => false,
                'notes' => 'مستخدم في اللغة العربية الحديثة والكلاسيكية.',
                'status' => 'draft',
                'created_by' => null,
                'updated_by' => null,
            ],
            [
                'name' => 'لـ', 
                'transliteration' => 'li', 
                'pronunciation' => '/li:/', 
                'meaning' => 'لـ',
                'definition' => 'تستخدم للإظهار الغرض أو السبب.',
                'category_id' => 2, // حروف الجر
                'syntactic_effect_id' => 2,
                'semantic_logical_effect_id' => 2,
                'morphological_form' => 'حرف جر',
                'typical_nisbah' => 'لام',
                'primary_usage' => 'التعليل',
                'grammatical_function' => 'حرف جر',
                'position' => 'start',
                'connective_form' => 'connected',
                'is_classical' => true,
                'notes' => 'تستخدم للتعبير عن السبب.',
                'status' => 'draft',
                'created_by' => null,
                'updated_by' => null,
            ],
            [
                'name' => 'إذا', 
                'transliteration' => 'idha', 
                'pronunciation' => '/idhan/', 
                'meaning' => 'إذا',
                'definition' => 'تستخدم للتعبير عن الشرط.',
                'category_id' => 3, // أدوات الشرط
                'syntactic_effect_id' => 3,
                'semantic_logical_effect_id' => 3,
                'morphological_form' => 'حرف شرط',
                'typical_nisbah' => 'إذا',
                'primary_usage' => 'الشرط',
                'grammatical_function' => 'شرطية',
                'position' => 'start',
                'connective_form' => 'standalone',
                'is_classical' => true,
                'notes' => 'مستخدمة في الجمل الشرطية.',
                'status' => 'draft',
                'created_by' => null,
                'updated_by' => null,
            ],
            [
                'name' => 'أو', 
                'transliteration' => 'aw', 
                'pronunciation' => '/aw/', 
                'meaning' => 'أو',
                'definition' => 'تستخدم للاختيار بين خيارين أو أكثر.',
                'category_id' => 1, // حروف العطف
                'syntactic_effect_id' => 5,
                'semantic_logical_effect_id' => 5,
                'morphological_form' => 'جزء',
                'typical_nisbah' => 'أو',
                'primary_usage' => 'الاختيار',
                'grammatical_function' => 'رابط',
                'position' => 'middle',
                'connective_form' => 'standalone',
                'is_classical' => false,
                'notes' => 'مستخدم في اللغة العربية الحديثة والكلاسيكية.',
                'status' => 'draft',
                'created_by' => null,
                'updated_by' => null,
            ],
            [
                'name' => 'من', 
                'transliteration' => 'min', 
                'pronunciation' => '/min/', 
                'meaning' => 'من',
                'definition' => 'تستخدم للتعبير عن الانتماء أو الجزء من الكل.',
                'category_id' => 2, // حروف الجر
                'syntactic_effect_id' => 6,
                'semantic_logical_effect_id' => 6,
                'morphological_form' => 'حرف جر',
                'typical_nisbah' => 'ميم',
                'primary_usage' => 'التعبير عن الجزء',
                'grammatical_function' => 'حرف جر',
                'position' => 'start',
                'connective_form' => 'connected',
                'is_classical' => true,
                'notes' => 'تستخدم للإشارة إلى الجزء من شيء.',
                'status' => 'draft',
                'created_by' => null,
                'updated_by' => null,
            ],
            [
                'name' => 'إن', 
                'transliteration' => 'in', 
                'pronunciation' => '/in/', 
                'meaning' => 'إن',
                'definition' => 'تستخدم للتعبير عن الشرط أو التوكيد.',
                'category_id' => 3, // أدوات الشرط
                'syntactic_effect_id' => 7,
                'semantic_logical_effect_id' => 7,
                'morphological_form' => 'حرف شرط',
                'typical_nisbah' => 'إن',
                'primary_usage' => 'التوكيد أو الشرط',
                'grammatical_function' => 'شرطية',
                'position' => 'start',
                'connective_form' => 'standalone',
                'is_classical' => true,
                'notes' => 'تستخدم في الجمل الشرطية أو للتوكيد.',
                'status' => 'draft',
                'created_by' => null,
                'updated_by' => null,
            ],
            [
                'name' => 'بل', 
                'transliteration' => 'bal', 
                'pronunciation' => '/bal/', 
                'meaning' => 'بل',
                'definition' => 'تستخدم للتصحيح أو التأكيد على النقيض.',
                'category_id' => 4, // حروف الاستدراك
                'syntactic_effect_id' => 8,
                'semantic_logical_effect_id' => 8,
                'morphological_form' => 'حرف استدراك',
                'typical_nisbah' => 'باء',
                'primary_usage' => 'التصحيح',
                'grammatical_function' => 'استدراك',
                'position' => 'middle',
                'connective_form' => 'standalone',
                'is_classical' => true,
                'notes' => 'تستخدم لتصحيح معلومة أو للتأكيد على النقيض.',
                'status' => 'draft',
                'created_by' => null,
                'updated_by' => null,
            ],
            [
                'name' => 'فَ', 
                'transliteration' => 'fa', 
                'pronunciation' => '/fa:/', 
                'meaning' => 'فَ',
                'definition' => 'تستخدم للإظهار الترتيب أو النتيجة.',
                'category_id' => 1, // حروف العطف
                'syntactic_effect_id' => 9,
                'semantic_logical_effect_id' => 9,
                'morphological_form' => 'جزء',
                'typical_nisbah' => 'فاء',
                'primary_usage' => 'الترتيب',
                'grammatical_function' => 'رابط',
                'position' => 'middle',
                'connective_form' => 'standalone',
                'is_classical' => true,
                'notes' => 'تستخدم للتعبير عن الترتيب أو النتيجة.',
                'status' => 'draft',
                'created_by' => null,
                'updated_by' => null,
            ],
            [
                'name' => 'على', 
                'transliteration' => 'ala', 
                'pronunciation' => '/alaa/', 
                'meaning' => 'على',
                'definition' => 'تستخدم للتعبير عن المكان أو الحالة.',
                'category_id' => 2, // حروف الجر
                'syntactic_effect_id' => 10,
                'semantic_logical_effect_id' => 10,
                'morphological_form' => 'حرف جر',
                'typical_nisbah' => 'عين',
                'primary_usage' => 'المكان',
                'grammatical_function' => 'حرف جر',
                'position' => 'start',
                'connective_form' => 'connected',
                'is_classical' => true,
                'notes' => 'تستخدم للتعبير عن المكان أو الحالة.',
                'status' => 'draft',
                'created_by' => null,
                'updated_by' => null,
            ],
            [
                'name' => 'لو', 
                'transliteration' => 'law', 
                'pronunciation' => '/law/', 
                'meaning' => 'لو',
                'definition' => 'تستخدم للتعبير عن شرط غير محتمل.',
                'category_id' => 3, // أدوات الشرط
                'syntactic_effect_id' => 11,
                'semantic_logical_effect_id' => 11,
                'morphological_form' => 'حرف شرط',
                'typical_nisbah' => 'لام',
                'primary_usage' => 'شرط غير محتمل',
                'grammatical_function' => 'شرطية',
                'position' => 'start',
                'connective_form' => 'standalone',
                'is_classical' => true,
                'notes' => 'تستخدم في الجمل الشرطية للتعبير عن شرط غير محتمل.',
                'status' => 'draft',
                'created_by' => null,
                'updated_by' => null,
            ],
            [
                'name' => 'وَلَكِن', 
                'transliteration' => 'walakin', 
                'pronunciation' => '/walakin/', 
                'meaning' => 'وَلَكِن',
                'definition' => 'تظهر التناقض مع إضافة ترتيب.',
                'category_id' => 4, // حروف الاستدراك
                'syntactic_effect_id' => 12,
                'semantic_logical_effect_id' => 12,
                'morphological_form' => 'حرف استدراك مركب',
                'typical_nisbah' => 'واو و لام',
                'primary_usage' => 'التناقض والترتيب',
                'grammatical_function' => 'استدراك',
                'position' => 'middle',
                'connective_form' => 'hybrid',
                'is_classical' => true,
                'notes' => 'مركب من و و لكن للتعبير عن التناقض مع الترتيب.',
                'status' => 'draft',
                'created_by' => null,
                'updated_by' => null,
            ],
            // Add more rows here to reach 16 or more...
        ];

        DB::table('connectives')->insert($connectives);
    }
}